name: CI

on:
  push:
    branches: [gitactions]
  pull_request:
    branches: [gitactions]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build WebService
        run: dotnet build ExampleWebService/ExampleWebService.csproj -c Release --no-restore

      - name: Build Test Project
        run: dotnet build ExampleTestProject/ExampleTestProject.csproj -c Release --no-restore

      - name: Publish WebService
        run: dotnet publish ExampleWebService/ExampleWebService.csproj -c Release -r linux-x64 --self-contained false -o publish --no-build --no-restore

      - name: Upload WebService artifact
        uses: actions/upload-artifact@v4
        with:
          name: webservice
          path: ExampleWebService/publish/

      - name: Run Tests
        run: dotnet test ExampleTestProject/ExampleTestProject.csproj --no-build --verbosity normal --no-restore
